plugins {
    id 'groovy'
    id 'application'
    id 'java-library'
}

apply plugin: 'org.apache.grails.gradle.grails-plugin'
// tag::applyGrailsPublish[]
apply plugin: 'org.apache.grails.gradle.grails-publish'
// end::applyGrailsPublish[]

repositories {
    mavenCentral()
    maven { url 'https://repo.grails.org/grails/core/' }
    maven { url 'https://repo.grails.org/grails/restricted' }
}
// tag::versionAndGroup[]
version = projectVersion
group = 'io.github.gpc'
// end::versionAndGroup[]

// tag::dependencies[]
dependencies {
    // Will prevent dependencies to become transient runtime dependencies
    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'
    // aggregates all web, non-test, non-database Grails dependencies.
    // Alternatively use 
    // compileOnly 'org.apache.grails:grails-dependencies' // aggregates all web, hibernate, database, non-test Grails dependencies.  

    // Artefacts you want to be transient runtime dependencies can be specified as
    implementation 'org.apache.commons:commons-lang3:3.19.0'

    // Artefacts you want to be transients implementation dependencies can be specified as
    api 'org.apache.commons:commons-lang3:3.19.0'
    // Just remember to apply the gradle java-library plugin

    // Needs to be defined again, as there are no implementation dependencies
    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
    testImplementation 'org.apache.grails:grails-dependencies-test' // aggregates all non-data test dependencies 
    testImplementation 'org.spockframework:spock-core'
}
// end::dependencies[]

application {
    mainClass.set 'release.demo.Application'
}

java {
    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    withJavadocJar()
    withSourcesJar()
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

// tag::grailsPublish[]
grailsPublish {
    githubSlug = 'gpc/release-demo'
    license {
        name = 'Apache-2.0'
    }
    title = 'Release Demo'
    desc = 'Release Demo for the GPC'
    developers = [
            sbglasius: "Søren Berg Glasius"
    ]
}
// end::grailsPublish[]

// tag::applyDocs[]
apply from: 'gradle/docs-config.gradle'
// end::applyDocs[]
// tag::applyPostPublish[]
apply from: 'gradle/post-publish.gradle'
// end::applyPostPublish[]
