plugins {
    id 'groovy-gradle-plugin'
}

file('../gradle.properties').withInputStream {
    def gradleProperties = new Properties()
    gradleProperties.load(it)
    gradleProperties.each { k, v -> ext.set(k, v) }
}

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
    maven { url "https://repo.grails.org/grails/restricted" }
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    implementation "org.apache.grails:grails-gradle-plugins"
}
