# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Check and publish snapshot

on:
    push:
        branches: [ master, main ]
    pull_request:
        branches: [ master, main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 11
            -   uses: gradle/gradle-build-action@v2
                env:
                    SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                    SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                    SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
                with:
                    arguments: publish